// <auto-generated />
using System;
using Layer.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Layer.Repositories.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230813110334_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Layer.Core.Models.CampaignChannels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CampaignsId")
                        .HasColumnType("int");

                    b.Property<int>("ChannelsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CampaignsId");

                    b.HasIndex("ChannelsId");

                    b.ToTable("CampaignChannels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampaignsId = 1,
                            ChannelsId = 1,
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8508),
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CampaignsId = 1,
                            ChannelsId = 2,
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8544),
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            CampaignsId = 2,
                            ChannelsId = 1,
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8548),
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CampaignsId = 4,
                            ChannelsId = 3,
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8550),
                            Status = false
                        });
                });

            modelBuilder.Entity("Layer.Core.Models.Campaigns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CampaignType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampaignType = "General",
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8623),
                            EndDate = new DateTime(23, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Test Kampanya 1",
                            Priority = 10,
                            StartDate = new DateTime(23, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true
                        },
                        new
                        {
                            Id = 2,
                            CampaignType = "CustomerSpecial",
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8629),
                            EndDate = new DateTime(23, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Test Kampanya 2",
                            Priority = 20,
                            StartDate = new DateTime(23, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = false
                        },
                        new
                        {
                            Id = 3,
                            CampaignType = "General",
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8632),
                            EndDate = new DateTime(23, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Test Kampanya 3",
                            Priority = 30,
                            StartDate = new DateTime(22, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = true
                        },
                        new
                        {
                            Id = 4,
                            CampaignType = "CustomerSpecial",
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8634),
                            EndDate = new DateTime(23, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Test Kampanya 4",
                            Priority = 40,
                            StartDate = new DateTime(23, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = false
                        });
                });

            modelBuilder.Entity("Layer.Core.Models.Channels", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChannelType = "MOBIL",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            ChannelType = "WEB",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            ChannelType = "EMAIL",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            ChannelType = "SMS",
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Layer.Core.Models.CustomerCampaigns", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CampaignsId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomersId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CampaignsId");

                    b.HasIndex("CustomersId");

                    b.ToTable("CustomerCampaigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CampaignsId = 4,
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8764),
                            CustomersId = 1
                        },
                        new
                        {
                            Id = 2,
                            CampaignsId = 3,
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8768),
                            CustomersId = 2
                        },
                        new
                        {
                            Id = 3,
                            CampaignsId = 3,
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8770),
                            CustomersId = 3
                        },
                        new
                        {
                            Id = 4,
                            CampaignsId = 2,
                            CreatedDate = new DateTime(2023, 8, 13, 14, 3, 33, 837, DateTimeKind.Local).AddTicks(8772),
                            CustomersId = 4
                        });
                });

            modelBuilder.Entity("Layer.Core.Models.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerNo")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Customer1",
                            CustomerNo = 1000
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Customer2",
                            CustomerNo = 1001
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Customer3",
                            CustomerNo = 1002
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Customer4",
                            CustomerNo = 1003
                        });
                });

            modelBuilder.Entity("Layer.Core.Models.Parameters", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParameterValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Parameters");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description1",
                            GroupCode = "GeneralCampaigns",
                            ParameterCode = "Public",
                            ParameterValue = "Genel Kampanya"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Description2",
                            GroupCode = "CustomerCampaigns",
                            ParameterCode = "Private",
                            ParameterValue = "Müşteri Bazlı Kampanya"
                        });
                });

            modelBuilder.Entity("Layer.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yavuz"
                        });
                });

            modelBuilder.Entity("Layer.Core.Models.CampaignChannels", b =>
                {
                    b.HasOne("Layer.Core.Models.Campaigns", "Campaigns")
                        .WithMany("CampaignChannels")
                        .HasForeignKey("CampaignsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Layer.Core.Models.Channels", "Channels")
                        .WithMany("CampaignChannels")
                        .HasForeignKey("ChannelsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaigns");

                    b.Navigation("Channels");
                });

            modelBuilder.Entity("Layer.Core.Models.CustomerCampaigns", b =>
                {
                    b.HasOne("Layer.Core.Models.Campaigns", "Campaigns")
                        .WithMany("CustomerCampaigns")
                        .HasForeignKey("CampaignsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Layer.Core.Models.Customers", "Customers")
                        .WithMany("CustomerCampaigns")
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaigns");

                    b.Navigation("Customers");
                });

            modelBuilder.Entity("Layer.Core.Models.Campaigns", b =>
                {
                    b.Navigation("CampaignChannels");

                    b.Navigation("CustomerCampaigns");
                });

            modelBuilder.Entity("Layer.Core.Models.Channels", b =>
                {
                    b.Navigation("CampaignChannels");
                });

            modelBuilder.Entity("Layer.Core.Models.Customers", b =>
                {
                    b.Navigation("CustomerCampaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
